# Generated by Django 4.0.2 on 2022-02-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('uname', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'USER'), (0, 'EXPERT')], default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1)),
            ],
        ),
    ]
